name: Release

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest,ubuntu-latest]
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - run: conda install -c conda-forge jpeg
      - run: conda install -c conda-forge libpng
      - run: conda install -c anaconda zlib
      - run: npm config set ignore-scripts true
      - run: npm install
      - run: npm run prebuild -- -u ${{ secrets.ORG_PREBUILD_TOKEN }}


  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: |
          echo "_auth=${{ secrets.ORG_NPM_TOKEN }}" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.ORG_NPM_TOKEN }}" >> .npmrc
      - run: npm publish --access public
        env:
            NODE_AUTH_TOKEN: ${{ secrets.ORG_NPM_TOKEN }}
        